### ISSUE TITLE
Create API endpoint to allow users to leave an organization

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#326]
## Summary
At the moment you cannot leave an organization once you're part of it, unless the administrator removes you.

## Behavior
Remove the `OrganizationMember` entry for this user in this organization

## Restrictions
You should only be able to remove your own `OrganizationMember` entry, not one that corresponds to different users. Aka you can only make yourself leave an organization and not anybody else

**Comment by akshatashan** [comment]
@positiveimpact 
I checked the backend and looks like the functionality already exists. Here is a sample curl request for the same. Is this a frontend ticket rather than backend ?

`curl -X DELETE 'http://192.168.0.19:8000/api/organizations/Organization2_x/update_member/2/' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Authorization: Token <auth token for user id: 2>' -H 'Origin: http://localhost:3000' -H 'Connection: keep-alive'`

**Comment by positiveimpact** [comment]
You're right! There is an additional frontend issue for this, so I'm closing this. Thanks for pointing this out!
