### ISSUE TITLE
Refactor follow functionality as it relates to project membership

### ISSUE THREAD

**Issue by piperchester** [climateconnect/climateconnect#703]
On October 5, 2021 we discussed this behavior as it relates to the #671 PR and feature. We decided that 

1. Any admin on a project, should be following that project by default
2. Any member of a project, should default to follow as well

**Comment by piperchester** [comment]
One question I have here for @positiveimpact and @ddhanesha -- what's the difference in the database between members and followers? Do we want to delineate between the two? As in, I could be a member of a project, but not necessarily following it.

**Comment by positiveimpact** [comment]
> 

Members are actively working on that project, followers are just interested in getting updates. With things like project progress posts coming up, implementing this would probably make sense.
I'd make members follow the project automatically when they join but allow them to unfollow. Otherwise you basically can't opt out of the update emails

**Comment by positiveimpact** [comment]
To rephrase this, the TODO of this issue is: "Make members automatically followers of a project"?
