### ISSUE TITLE
Bug: Organization page: edit button overlaps with organization image on tiny screens

### ISSUE THREAD

**Issue by verena-e-p** [climateconnect/climateconnect#802]
When the user is logged in on their own organization page and the screen is smaller than around 400 px in width, the edit organization button overlaps with the organization image.

(_As mentioned here: https://github.com/climateconnect/climateconnect/issues/792#issuecomment-986853834_)

After relocating the button, check if the CSS style change to the container of the SocialMediaShareButton on the organization account is still necessary. (_See commit: https://github.com/climateconnect/climateconnect/pull/792/commits/a74ded30d3c743997e95c0ab06993511144a6c23_)

**Comment by positiveimpact** [comment]
Steps to reproduce:
1. Create an account by signing up on your local platform
2. Create an organization on /createorganization
3. Go to the organization's page with a screen resolution of less than 400px

Additionally to the edit button overlapping, the "Share a project" button is also looking a bit weird on small mobile screens. It could be worth it to just display "Share" instead of "Share a project" on tiny screens (breakpoint xs)

Image for context:
![Uploading Screenshot from 2022-02-25 18-36-05.png…]()

**Comment by tobiasrehm** [comment]
Was fixed. But there is still a bug related to this: #1199. Closing this one
